5.สร้างแบบจำลอง association rule หรือ market basket เพื่อวิเคราะห์ความสัมพันธ์ของสินค้าที่ถูกส่วน
ด้วยกัน

In [39]:
import pandas as pd
df = pd.read_csv('transaction_data_clean.csv') # Load ข้อมูลที่ Clean แล้วขึ้นมา

In [40]:
df

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
0,278166,6355745,Sat Feb 02 12:50:00 IST 2019,465549,FAMILY ALBUM WHITE PICTURE FRAME,6,11.73,United Kingdom
1,337701,6283376,Wed Dec 26 09:06:00 IST 2018,482370,LONDON BUS COFFEE MUG,3,3.52,United Kingdom
2,267099,6385599,Fri Feb 15 09:45:00 IST 2019,490728,SET 12 COLOUR PENCILS DOLLY GIRL,72,0.90,France
3,380478,6044973,Fri Jun 22 07:14:00 IST 2018,459186,UNION JACK FLAG LUGGAGE TAG,3,1.73,United Kingdom
4,285957,6307136,Fri Jan 11 09:50:00 IST 2019,1787247,CUT GLASS T-LIGHT HOLDER OCTAGON,12,3.52,United Kingdom
...,...,...,...,...,...,...,...,...
1586007,261681,6153092,Wed Sep 19 06:23:00 IST 2018,477330,ALARM CLOCK BAKELIKE IVORY,12,5.18,Switzerland
1586008,313131,6040298,Mon Jun 18 09:18:00 IST 2018,437976,DENIM PATCH PURSE PINK BUTTERFLY,30,2.28,EIRE
1586009,295743,6387117,Sat Feb 16 09:14:00 IST 2019,484113,RECYCLED ACAPULCO MAT PINK,6,11.39,United Kingdom
1586010,324765,5945500,Fri Mar 23 06:26:00 IST 2018,470883,REGENCY CAKESTAND 3 TIER,48,15.12,United Kingdom
1586011,351645,6118145,Tue Aug 21 08:21:00 IST 2018,471849,HEART OF WICKER SMALL,9,2.28,United Kingdom

In [41]:
# Convert the data to a transaction format
transactions = df.groupby('TransactionId')['ItemDescription'].apply(list).reset_index(name='Items')

In [42]:
transactions

       TransactionId                                              Items
0            5900015  [SET 7 BABUSHKA NESTING BOXES, WHITE METAL LAN...
1            5900026  [HAND WARMER RED POLKA DOT, HAND WARMER UNION ...
2            5900037  [DOORMAT NEW ENGLAND, HOME BUILDING BLOCK WORD...
3            5900048  [BLUE COAT RACK PARIS FASHION, RED COAT RACK P...
4            5900059  [BATH BUILDING BLOCK WORD, BATH BUILDING BLOCK...
...              ...                                                ...
18403        6397413  [6 CHOCOLATE LOVE HEART T-LIGHTS, LUNCH BAG RE...
18404        6397424  [RED FLOCK LOVE HEART PHOTO FRAME, RED FLOCK L...
18405        6397435  [MAGNETS PACK OF 4 SWALLOWS, LARGE CHINESE STY...
18406        6397446  [LARGE CAKE STAND  HANGING STRAWBERY, LARGE CA...
18407        6397457  [PACK OF 20 SPACEBOY NAPKINS, ALARM CLOCK BAKE...

[18408 rows x 2 columns]

In [44]:
# Convert the transaction data to a one-hot encoded format
transactions_encoded = pd.get_dummies(transactions['Items'].explode()).groupby(level=0).max()

In [45]:
transactions_encoded

,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,I LOVE LONDON MINI RUCKSACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18403,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18404,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18405,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
18406,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18407,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [50]:
# Apply Apriori algorithm
frequent_itemsets = apriori(transactions_encoded, min_support=0.1, use_colnames=True)

# Generate association rules

In [51]:
frequent_itemsets

    support                              itemsets
0  0.107073  (WHITE HANGING HEART T-LIGHT HOLDER)

In [65]:
# Print frequent_itemsets to inspect
print("Frequent Itemsets:")
print(frequent_itemsets)

# Generate association rules
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.1)

# Display the association rules
print("Association Rules:")
print(rules)

# จาก Output: Frequent Itemsets= WHITE HANGING HEART T-LIGHT HOLDER ,0.107073(10.71%)
# หมายถึง สินค้า WHITE HANGING HEART T-LIGHT HOLDER เป็นที่นิยม มี 10.71% ของข้อมูลทั้งหมด
# ส่วน Association Rules: = Empty DataFrame หมายถึง สินค้าต่างๆ ไม่มีความสัมพันธ์ต่อกัน

Frequent Itemsets:
    support                              itemsets
0  0.107073  (WHITE HANGING HEART T-LIGHT HOLDER)
Association Rules:
Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction, zhangs_metric]
Index: []

In [57]:
# ดูข้อมูลที่ column:ItemDescription = WHITE HANGING HEART T-LIGHT HOLDER
filtered_rows = df[df['ItemDescription'] == 'WHITE HANGING HEART T-LIGHT HOLDER']

# Display the filtered rows
filtered_rows
# มี TransactionId ที่ ItemDescription คือ WHITE HANGING HEART T-LIGHT HOLDER เหมือนๆกัน 8,112 ข้อมูล

,UserId,TransactionId,TransactionTime,ItemCode,ItemDescription,NumberOfItemsPurchased,CostPerItem,Country
65,370314,6076884,Sat Jul 21 09:10:00 IST 2018,1787583,WHITE HANGING HEART T-LIGHT HOLDER,9,4.08,United Kingdom
344,306327,5950483,Mon Mar 26 09:16:00 IST 2018,1787583,WHITE HANGING HEART T-LIGHT HOLDER,3,4.08,United Kingdom
543,269934,6048284,Sun Jun 24 10:17:00 IST 2018,1787583,WHITE HANGING HEART T-LIGHT HOLDER,9,4.08,United Kingdom
565,275310,5998564,Sun May 13 10:58:00 IST 2018,1787583,WHITE HANGING HEART T-LIGHT HOLDER,15,4.08,United Kingdom
1162,276528,6316717,Tue Jan 15 08:56:00 IST 2019,1787583,WHITE HANGING HEART T-LIGHT HOLDER,18,4.08,United Kingdom
...,...,...,...,...,...,...,...,...
1585102,295785,5924974,Sat Feb 24 09:28:00 IST 2018,1787583,WHITE HANGING HEART T-LIGHT HOLDER,12,4.08,United Kingdom
1585404,345786,6121181,Fri Aug 24 07:47:00 IST 2018,1787583,WHITE HANGING HEART T-LIGHT HOLDER,18,4.08,United Kingdom
1585666,264264,6307015,Fri Jan 11 09:13:00 IST 2019,1787583,WHITE HANGING HEART T-LIGHT HOLDER,36,4.08,Italy
1585911,351855,6199105,Mon Oct 29 09:21:00 IST 2018,1787583,WHITE HANGING HEART T-LIGHT HOLDER,30,4.08,United Kingdom
1585978,355026,6038813,Sun Jun 17 08:30:00 IST 2018,1787583,WHITE HANGING HEART T-LIGHT HOLDER,12,4.08,United Kingdom